Removed some unecessary use of streaming that was causing an error in the depths of the std library.
Fixes this error:

Failed to load zip file z:\photos\Photo Library\Carseldine Unit\Unit - slab air con solar unit.zip
TypeError: undefined is not a function (near '...chunk of stream...')
    at blob (node:stream/consumers:7:24)
    at blob (node:stream/consumers:3:21)
    at arrayBuffer (node:stream/consumers:14:21)
    at arrayBuffer (node:stream/consumers:11:28)
    at buffer (node:stream/consumers:22:40)
    at buffer (node:stream/consumers:21:23)
    at scanZipFile (C:\projects\photosphere\packages\api\src\lib\file-scanner.ts:195:46)
    at async scanZipFile (C:\projects\photosphere\packages\api\src\lib\file-scanner.ts:228:23)
    at async scanPathInternal (C:\projects\photosphere\packages\api\src\lib\file-scanner.ts:371:19)
    at async scanPaths (C:\projects\photosphere\packages\api\src\lib\file-scanner.ts:412:15)
    at async checkPaths (C:\projects\photosphere\packages\api\src\lib\check.ts:87:15)
    at async checkCommand (C:\projects\photosphere\apps\cli\src\cmd\check.ts:40:30)
    at processTicksAndRejections (native:7:39)